### ISSUE TITLE
How to reset store on logout?

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [randallknutson/redux-injector#8]
I am trying to reset my store using the method shown here -> https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store

**Comment by randallknutson** [comment]
I typically handle this as part of the reducers, not the store level. Something along the line of listening in each reducer for a 'USER_LOGOUT' and clearing data. This doesn't affect this library though.
